//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameIn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeZones
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public short UTCOffset { get; set; }
        public string WindowsID { get; set; }
    }
}
