//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameIn.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    using App_GlobalResources;

    public partial class Users
    {
        public long ID { get; set; }

        [Display(ResourceType = typeof(Resources), Name = "Email")]
        [Required(AllowEmptyStrings = false, ErrorMessageResourceName = "RequiredField",
            ErrorMessageResourceType = typeof(Resources))]
        public string Email { get; set; }

        [Display(ResourceType = typeof(Resources), Name = "Username")]
        [Required(AllowEmptyStrings = false, ErrorMessageResourceName = "RequiredField",
            ErrorMessageResourceType = typeof(Resources))]
        public string UserName { get; set; }

        [Display(ResourceType = typeof(Resources), Name = "Password")]
        [Required(AllowEmptyStrings = false, ErrorMessageResourceName = "RequiredField",
            ErrorMessageResourceType = typeof(Resources))]
        public string Password { get; set; }
        public byte Type { get; set; }
        public string Name { get; set; }
        public bool Gender { get; set; }
        public bool Status { get; set; }
        public SelectListItem Countries { get; set; }
        public int? CountryID { get; set; }
        public SelectListItem States { get; set; }
        public int? StateID { get; set; }
        public int? Region { get; set; }
        public string SubRegion { get; set; }
        public byte Lang { get; set; }
        public string TimeZone { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string LastIP { get; set; }
        public string LastUserAgent { get; set; }
    }
}
